
#Configs for weapons that currently mod has to offer and can be found in survival
[current_weapons]

	[current_weapons.abyssal_tidecaller]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 21.0
		#Range: 0.0 ~ 100.0
		damage = 21.0
		#Attack Speed || Default -3.0
		#Range: -5.0 ~ 5.0
		attack_speed = -3.0
		#Eldritch Spell Power || MULTIPLY_TOTAL || Default 0.15
		#Range: 0.0 ~ 1.0
		eldritch_spell_power = 0.15
		#Ender Spell Power || MULTIPLY_TOTAL || Default 0.10
		#Range: 0.0 ~ 1.0
		ender_spell_power = 0.1

	[current_weapons.flames_of_eldritch]
		#Durability || Default 3000
		#Range: > 1
		durability = 3000
		#Damage || Default 17.0
		#Range: 0.0 ~ 100.0
		damage = 17.0
		#Attack Speed || Default -2.6
		#Range: -5.0 ~ 5.0
		attack_speed = -2.6
		#Eldritch Spell Power || MULTIPLY_TOTAL || Default 0.05
		#Range: 0.0 ~ 1.0
		eldritch_spell_power = 0.05
		#Fire Spell Power || MULTIPLY_TOTAL || Default 0.20
		#Range: 0.0 ~ 1.0
		fire_spell_power = 0.2

	[current_weapons.harbingers_wrath]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 17.0
		#Range: 0.0 ~ 100.0
		damage = 17.0
		#Attack Speed || Default -2.8
		#Range: -5.0 ~ 5.0
		attack_speed = -2.8
		#Lightning Spell Power || MULTIPLY_TOTAL || Default 0.20
		#Range: 0.0 ~ 1.0
		lightning_spell_power = 0.2

	[current_weapons.scourge_of_the_sands]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 13.0
		#Range: 0.0 ~ 100.0
		damage = 13.0
		#Attack Speed || Default -2.4
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Evocation Spell Power || MULTIPLY_TOTAL || Default 0.10
		#Range: 0.0 ~ 1.0
		evocation_spell_power = 0.1
		#Nature Spell Power || MULTIPLY_TOTAL || Default 0.10
		#Range: 0.0 ~ 1.0
		nature_spell_power = 0.1

	[current_weapons.thorns_of_oblivion]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 13.0
		#Range: 0.0 ~ 100.0
		damage = 13.0
		#Attack Speed || Default -2.4
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Nature Spell Power || MULTIPLY_TOTAL || Default 0.05
		#Range: 0.0 ~ 1.0
		nature_spell_power = 0.15
		#Ender Spell Power || MULTIPLY_TOTAL || Default 0.05
		#Range: 0.0 ~ 1.0
		ender_spell_power = 0.15

	[current_weapons.voidstrike_reaper]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 19.0
		#Range: 0.0 ~ 100.0
		damage = 19.0
		#Attack Speed || Default -3.0
		#Range: -5.0 ~ 5.0
		attack_speed = -3.0
		#Ender Spell Power || MULTIPLY_BASE || Default 0.10
		#Range: 0.0 ~ 1.0
		ender_spell_power = 0.2

#W.I.P Weapons Config
#These wip weapon are work-in-progress and can not be accessed in game by any means.
#This is for DEV purposes.. you should IGNORE this portion!
[wip_weapons]

	[wip_weapons.blazegrip_scimitar]
		#Durability || Default 2000
		#Range: > 1
		durability = 2000
		#Damage || Default 13.0
		#Range: 0.0 ~ 100.0
		damage = 1.0
		#Attack Speed || Default -2.6
		#Range: -5.0 ~ 5.0
		attack_speed = -2.6
		#Fire Damage || ADDITION || Default 2.0
		#Range: 0.0 ~ 10.0
		fire_damage = 2.0
		#Fire Spell Power || MULTIPLY_TOTAL || Default 0.10
		#Range: 0.0 ~ 1.0
		fire_spell_power = 0.1

	[wip_weapons.bloodbound_carnage]
		#Durability || Default 2000
		#Range: > 1
		durability = 2000
		#Damage || Default 11.0
		#Range: 0.0 ~ 100.0
		damage = 11.0
		#Attack Speed || Default -2.4
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Blood Spell Power || MULTIPLY_TOTAL || Default 0.15
		#Range: 0.0 ~ 1.0
		blood_spell_power = 0.15

	[wip_weapons.celestial_edge]
		#Durability || Default 2000
		#Range: > 1
		durability = 2000
		#Damage || Default 15.0
		#Range: 0.0 ~ 100.0
		damage = 15.0
		#Attack Speed || Default -2.8
		#Range: -5.0 ~ 5.0
		attack_speed = -2.8
		#Holy Spell Power || MULTIPLY_TOTAL || Default 0.10
		#Range: 0.0 ~ 1.0
		holy_spell_power = 0.1

	[wip_weapons.cthonic_pulverizer]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 25.0
		#Range: 0.0 ~ 100.0
		damage = 25.0
		#Attack Speed || Default -3.2
		#Range: -5.0 ~ 5.0
		attack_speed = -3.2
		#Ice Spell Power || MULTIPLY_TOTAL || Default 0.20
		#Range: 0.0 ~ 1.0
		ice_spell_power = 0.2

	[wip_weapons.electro_whisperer]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 13.0
		#Range: 0.0 ~ 100.0
		damage = 13.0
		#Attack Speed || Default -2.4
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Lightning Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		lightning_spell_power = 0.2

	[wip_weapons.ethereal_edge]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 17.0
		#Range: 0.0 ~ 100.0
		damage = 17.0
		#Attack Speed || Default -2.8
		#Range: -5.0 ~ 5.0
		attack_speed = -2.8
		#Eldritch Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		eldritch_spell_power = 0.2

	[wip_weapons.frozen_scythe_of_silence]
		#Durability || Default 2000
		#Range: > 1
		durability = 2000
		#Damage || Default 17.0
		#Range: 0.0 ~ 100.0
		damage = 17.0
		#Attack Speed || Default -3.0
		#Range: -5.0 ~ 5.0
		attack_speed = -3.0
		#Ice Spell Power || MULTIPLY_BASE || Default 0.10
		#Range: 0.0 ~ 1.0
		ice_spell_power = 0.1

	[wip_weapons.gaias_harbinger]
		#Durability || Default 2000
		#Range: > 1
		durability = 2000
		#Damage || Default 11.0
		#Range: 0.0 ~ 100.0
		damage = 11.0
		#Attack Speed || Default -2.4
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Nature Spell Power || MULTIPLY_BASE || Default 0.10
		#Range: 0.0 ~ 1.0
		nature_spell_power = 0.1

	[wip_weapons.hammer_of_the_raging_storms]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 25.0
		#Range: 0.0 ~ 100.0
		damage = 25.0
		#Attack Speed || Default -3.2
		#Range: -5.0 ~ 5.0
		attack_speed = -3.2
		#Lightning Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		lightning_spell_power = 0.2

	[wip_weapons.lance_of_the_outer_realms]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 13.0
		#Range: 0.0 ~ 100.0
		damage = 13.0
		#Attack Speed || Default -2.4
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Eldritch Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		eldritch_spell_power = 0.2

	[wip_weapons.noxious_thicket]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 21.0
		#Range: 0.0 ~ 100.0
		damage = 21.0
		#Attack Speed || Default -3.0
		#Range: -5.0 ~ 5.0
		attack_speed = -3.0
		#Nature Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		nature_spell_power = 0.2

	[wip_weapons.scarlet_shadowcleaver]
		#Durability || Default 3000
		#Range: > 1
		durability = 3000
		#Damage || Default 23.0
		#Range: 0.0 ~ 100.0
		damage = 23.0
		#Attack Speed || Default -3.0
		#Range: -5.0 ~ 5.0
		attack_speed = -3.0
		#Life Steal || ADDITION || Default 0.20
		#Range: 0.0 ~ 1.0
		life_steal = 0.05
		#Blood Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		blood_spell_power = 0.2

	[wip_weapons.sorcerers_hexblade]
		#Durability || Default 1500
		#Range: > 1
		durability = 1500
		#Damage || Default 8.0
		#Range: 0.0 ~ 100.0
		damage = 8.0
		#Attack Speed || Default -2.2
		#Range: -5.0 ~ 5.0
		attack_speed = -2.2
		#Evocation Spell Power || MULTIPLY_BASE || Default 0.05
		#Range: 0.0 ~ 1.0
		evocation_spell_power = 0.05

	[wip_weapons.spear_of_the_eternal_flames]
		#Durability || Default 2500
		#Range: > 1
		durability = 2500
		#Damage || Default 13.0
		#Range: 0.0 ~ 100.0
		damage = 13.0
		#Attack Speed || Default -2.4
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Fire Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		fire_spell_power = 0.2

	[wip_weapons.stygian_eclipse]
		#Durability || Default 2500
		#Range: > 1
		durability = 2000
		#Damage || Default 13.0
		#Range: 0.0 ~ 100.0
		damage = 13.0
		#Attack Speed || Default -2.4
		#Range: -5.0 ~ 5.0
		attack_speed = -2.4
		#Ender Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		ender_spell_power = 0.2

