
#Staff, Spellbooks and other this kind of thing
[staff_spellbooks]

	[staff_spellbooks.titanlord_scepter]
		#Damage || Default 9.0
		#Range: 0.0 ~ 100.0
		damage = 9.0
		#Attack Speed || Default -3.0
		#Range: -5.0 ~ 5.0
		attack_speed = -3.0
		#Lightning Spell Power || MULTIPLY_BASE || Default 0.15
		#Range: 0.0 ~ 1.0
		lightning_spell_power = 0.15
		#Eldritch Spell Power || MULTIPLY_BASE || Default 0.15
		#Range: 0.0 ~ 1.0
		eldritch_spell_power = 0.15
		#Mana Regen || MULTIPLY_BASE || Default 0.10
		#Range: 0.0 ~ 1.0
		mana_regen = 0.1

	[staff_spellbooks.archive_of_abyssal_secrets]
		#Ender Spell Power || MULTIPLY_BASE || Default 0.10
		#Range: 0.0 ~ 1.0
		ender_spell_power = 0.1
		#Eldritch Spell Power || MULTIPLY_BASE || Default 0.10
		#Range: 0.0 ~ 1.0
		eldritch_spell_power = 0.1

	[staff_spellbooks.chronicles_of_the_firelord]
		#Fire Spell Power || MULTIPLY_BASE || Default 0.20
		#Range: 0.0 ~ 1.0
		fire_spell_power = 0.2
		#Spell Cooldown Reduction || MULTIPLY_BASE || Default 0.05
		#Range: 0.0 ~ 1.0
		cooldown_reduction = 0.05

	[staff_spellbooks.tome_of_abyssal_flora]
		#Ender Spell Power || MULTIPLY_BASE || Default 0.10
		#Range: 0.0 ~ 1.0
		ender_spell_power = 0.1
		#Nature Spell Power || MULTIPLY_BASE || Default 0.10
		#Range: 0.0 ~ 1.0
		nature_spell_power = 0.1

